branches: {only: [master, test]}

sudo: false
language: python
cache: pip

matrix:
  include:
    - python: "3.6"
    - python: "3.7-dev"
    - {python: "3.6", env: TOXENV=packaging}
    - {python: "3.6", env: TOXENV=style}
    - {python: "3.6", env: TOXENV=typing}

install: pip install tox-travis codecov
script: tox
after_success: codecov -e TRAVIS_PYTHON_VERSION
