#!/bin/sh
set -e

mydir=$(cd $(dirname "$0") && pwd)
base=$mydir/test_all_sample_images

cd "$mydir/.."
params=sample-images/params.yml
files=$(ls -1 sample-images/*.jpg | sort)

echo "Testing with $(echo "$files" | wc -l) files"

outdir=$(mktemp -d -t waterwatch_test.XXXXXX)

# Don't stop on errors
set +e

python3 -m waterwatch $params $files >"$outdir/stdout" 2>"$outdir/stderr"
exit_code=$?

diff -u "$base.expected_stdout" "$outdir/stdout"
diff_result1=$?

diff -u "$base.expected_stderr" "$outdir/stderr"
diff_result2=$?

# Set back stopping on errors
set -e

rm -fr "$outdir"

test "$exit_code" = "0"
test "$diff_result1" = "0"
test "$diff_result2" = "0"

echo "PASSED"
